version: "1"

cluster:
  provider: k3d
  minVersion: 4.0.0
  name: polls-helm
  nativeConfig:
    apiVersion: k3d.io/v1alpha2
    kind: Simple
    servers: 1
    agents: 1
    image: rancher/k3s:v1.22.9-k3s1
    ports:
      - port: 8080:80
        nodeFilters:
          - loadbalancer
      - port: 8443:443
        nodeFilters:
          - loadbalancer
      - port: 31820:31820/UDP
        nodeFilters:
          - agent[0]

decks:
  - name: polls
    namespace: default
    notes: |
      Welcome to the java-polls demo application, installed via helm. Once the app is ready, you can:

      - access the application: http://spring.127.0.0.1.nip.io:8080/
      - check out the api documentation: http://spring.127.0.0.1.nip.io:8080/swagger-ui/
      - add new questions, e.g. via Postman
    sources:
      - type: helm
        ref: https://raw.githubusercontent.com/Blueshoe/java-spring-example-charts/main/docs
        chart: polls
        releaseName: polls
        namespace: default
