apiVersion: v1
kind: Pod
metadata:
  name: busybox-1
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: "/var/nfs"
      name: nfs-volume
  restartPolicy: Always
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: nfs

---

apiVersion: v1
kind: Pod
metadata:
  name: busybox-2
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
    volumeMounts:
    - mountPath: "/var/nfs"
      name: nfs-volume
  restartPolicy: Always
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: nfs
